### ISSUE TITLE
Problem to find boost library

### ISSUE THREAD

**Issue by AndreSVargaS19** [DIDSR/VICTRE_PIPELINE#2]
Hello.

I followed the steps to install the VICTRE_PIPELINE, but, when i  execute the installation script (source install.sh) appears this error:
 - Checking boost 	NOT FOUND	*** You might not be able to compile breast generation, compression and mass generation on this computer.
 
then i edit the first lines on install.sh file:

BOOST_OPTIONS_LIB=/usr/share/doc/libboost-program-options-dev # route to libboost_program_options
VTK_DIR=/usr/local/lib
but the problem follows, What I should do to correct this problem? what path I should include in the install.sh file?

thanks for your attention.
Regards

**Comment by vanecka** [comment]
Hi André,

It is probably too late for you, but here is something to try:
Before running the **source install.sh** command, execute the following:

`
#### Set the paths according to your system
BOOST_INC=/usr/include/boost
BOOST_LIB=/usr/lib64
#### Although you didn't need this yet, I'm also setting the VTK options:
VTK_INC=/usr/include/vtk
VTK_LIB=/usr/lib64/vtk

#### The library and include paths of zlib and openmpi, can be read using the pkg-config command on my system,
#### so I execute the command and extract the values I require below.

#### If you don't intend to use OpenMPI, remove all the occurrences of the word **ompi**

export CFLAGS="$(pkg-config --cflags zlib ompi) -I$BOOST_INC -I$VTK_INC"
export LDFLAGS="$(pkg-config --libs zlib ompi)  -L$BOOST_LIB -L$VTK_LIB"
export MAKEFLAGS="-I$BOOST_INC -I$VTK_INC"

#####If you are using a GPU and want to compile MCGPU projection, I had to execute the following to specify my zlib paths:
export NVCC_PREPEND_FLAGS="$(pkg-config --cflags-only-I zlib ompi) $(pkg-config --libs-only-L zlib ompi)"

`
After executing the above, retry executing the **source install.sh** command.

**Comment by malago86** [comment]
Hi! Sorry for the late reply. Maybe you solved this thanks to @vanecka's response but in case you didn't, I updated the [install.sh](https://github.com/DIDSR/VICTRE_PIPELINE/blob/main/install.sh#L8) file so that it adds the `BOOST` library to the `C_INCLUDE_PATH` variable. It looks like that variable was not originally on the `install.sh` file!

`BOOST_INCLUDE=/usr/local/boost/ # route to boost source code`

Feel free to reopen this issue if you still have issues.
