### ISSUE TITLE
Run pipeline in a phantom without lesions (compression step issue)

### ISSUE THREAD

**Issue by javierlopezrodriguez** [DIDSR/VICTRE_PIPELINE#4]
Hello,

I am attempting to run the compression step in the VICTRE pipeline to compress a phantom without lesions, and I am encountering errors during the compression step when dealing with the `.loc` file. Here are the specific issues:

1. **When there is no `.loc` file**:  
   I receive the following error message:

   ```
   Error while compressing, check the output_compression.out file in the results folder
   Traceback (most recent call last):
     File "VICTRE_PIPELINE/example_compression.py", line 20, in <module>
       pline.compress_phantom(thickness=50)
     File "VICTRE_PIPELINE/Victre/Pipeline.py", line 1969, in compress_phantom
       raise Exceptions.VictreError("Compression error")
   Victre.Exceptions.VictreError: Compression error
   ```

   The corresponding `output_compression.out` file contains:
   ```
   Segmentation fault (core dumped)
   ```

2. **When the `.loc` file is empty**:  
   I receive this warning and error:

   ```
   VICTRE_PIPELINE/Victre/Pipeline.py:364: UserWarning: loadtxt: input contained no data: "example_phantom/3/p_3.loc"
     locations = np.loadtxt(
   Traceback (most recent call last):
     File "VICTRE_PIPELINE/example_compression.py", line 14, in <module>
       pline = Pipeline(seed=seed,
               ^^^^^^^^^^^^^^^^^^^
     File "VICTRE_PIPELINE/Victre/Pipeline.py", line 392, in __init__
       if not (type(locations[0]) is list or type(locations[0]) is np.ndarray):
                    ~~~~~~~~~^^^
   IndexError: index 0 is out of bounds for axis 0 with size 0
   ```

Since I am working with a phantom that contains no lesions, I would like to know how to correctly configure the pipeline in this scenario to avoid these errors. Could you please provide guidance on:
- How to handle or bypass the `.loc` file requirement for cases with no lesion data.
- Ensuring the compression step works correctly in phantoms without lesions.

Here is the code I'm using:

```{python}
from Victre import Pipeline
from Victre import Constants

seed = 3
results_folder = "results_example"
original_phantom = f"{results_folder}/{seed}/p_{seed}.raw.gz" # results/seed/file

pline = Pipeline(seed=seed,
                 phantom_file=original_phantom,
                 results_folder=results_folder)

# phantom is already generated, compress now

pline.compress_phantom(thickness=50)
pline.crop()
```

Thank you in advance for your assistance!

Best regards,  
Javier

**Comment by malago86** [comment]
Hi Javier,

The .loc file that is generated with the phantom is not for lesions inserted, it is a [list of candidate locations based on the TDLU](https://breastphantom.readthedocs.io/en/latest/output.html) for potential lesion insertion.

That file should not be missing, regardless of your intention to insert lesions or not. If you don't have that file or are using phantoms not generated with the VICTRE pipeline, maybe you can manually make the corresponding .loc file and add a single location on 0,0,0 (just 1 line of text with three numbers separated by a comma, [like this](https://github.com/DIDSR/VICTRE_PIPELINE/blob/main/phantoms/p_1.loc)). That will not interfere at all with the rest of the pipeline unless you are inserting lesions. It could be a quick workaround to avoid the errors you are getting.

If you are still getting errors, let me know!

**Comment by javierlopezrodriguez** [comment]
Hello,

Thank you for your help!

Following your suggestion (using a `.loc` file with a single line: `0,0,0`) allowed me to successfully compress the phantom. However, I encountered an error during the cropping step:

```
Traceback (most recent call last):
  File "VICTRE_PIPELINE/example_compression.py", line 34, in <module>
    pline.compress_phantom(thickness=50)
  File "VICTRE_PIPELINE/Victre/Pipeline.py", line 1996, in compress_phantom
    self.candidate_locations = self._mm_to_voxels(np.loadtxt(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VICTRE_PIPELINE/Victre/Pipeline.py", line 2218, in _mm_to_voxels
    locations[idx] = [int(np.round((cand[0] - self.mhd['Offset'][0]) /
                                    ~~~~^^^
TypeError: 'float' object is not subscriptable
```

However, I found that adding **two lines** of `0,0,0` to the `.loc` file instead of one resolved the issue.

Thanks again for your support!

Best regards,  
Javier

**Comment by malago86** [comment]
The way the file is read I think it needs more than 1 location on the file, add another line with 0,0,0 so two lines:

```
0,0,0
0,0,0
```
